### ISSUE TITLE
Complete FBU Requirements

### ISSUE THREAD

**Issue by cgnov** [cgnov/pomfocus#16]
Reference: [FBU App Expectations](https://courses.codepath.org/courses/android_university_fast_track/pages/fbu_app_expectations)
- [x] Your app has multiple views (#3, completed Sprint 1)
- [x] Your app interacts with a database (e.g. Parse) (#1, completed Sprint 1)
- [x] You can log in/log out of your app as a user (#4, completed Sprint 1)
- [x] You can sign up with a new user profile (#4, completed Sprint 1)
- [x] Somewhere in your app you can use the camera to take a picture and do something with the picture (e.g. take a photo and share it to a feed, or take a photo and set a user’s profile picture) (#5, completed Sprint 1, used for changing user's profile picture)
- [x] Your app integrates with a SDK (e.g. Google Maps SDK, Facebook SDK) (#11, completed Sprint 1, used Parse, Facebook, and Parse-Facebook SDKs for Facebook login)
- [x] Your app contains at least one more complex algorithm (talk over this with your manager)
- [x] Your app uses gesture recognizers (#15, e.g. double tap to like, e.g. pinch to scale)
- [x] Your app use an animation (doesn’t have to be fancy) (#9, e.g. fade in/out, e.g. animating a view growing and shrinking)
- [x] Your app incorporates an external library to add visual polish (#18, #19, MPAndroidChart in History)
